# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoRightNow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoRightNow
  pod 'Alamofire', '~> 5.5'


  target 'GoRightNowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoRightNowUITests' do
    # Pods for testing
  end

end
